### ISSUE TITLE
Checking "Musicnn" option causes errors and submission to fail

### ISSUE THREAD

**Issue by gingerbeardman** [intamixx/matnn#1]
If I check the "Musicnn" option I get errors:

Request failed with status code 400

<img width="482" alt="Screen shot 2024-06-28 at 15 33 52" src="https://github.com/intamixx/matnn/assets/49612/4baf5ed5-0829-41d7-87a2-c4dbff629c82">

After that I see an overlay with:

> Uncaught runtime errors:
> 
> ERROR
> undefined is not an object (evaluating 'delete tagobj.tags.genre_musicnn')
> handleMusicnnCheckboxChange@
> callWithErrorHandling@
> callWithAsyncErrorHandling@
> invoker@

- I have to refresh the page and start again
- I must not check the "Musicnn" option to get results

Thanks for this very useful service!

**Comment by intamixx** [comment]
Thanks, yes was aware of the vue app issue caused after a 400 (bad request) occurs.  I have put in a quick window reload if an error occurs to quickly reload the page and reset the form variables.
https://github.com/intamixx/matnn/commit/4f55a372d91ded61c50deab6ebf33af46bf8021b
There is the a basic html version of the form at https://matnn.intamixx.uk/upload if that suits better.

**Comment by gingerbeardman** [comment]
My issue was more that every time I select "Musicnn" I get the 400 error. Is that expected?

**Comment by intamixx** [comment]
I can't recreate the error (i've tried 2 different browsers), is it only happening with that checkbox or the others as well?

**Comment by gingerbeardman** [comment]
Here's a screen recording

- file specified
- all check marks selected
- Safari 17.5 on macOS 14.5

https://github.com/intamixx/matnn/assets/49612/8bcc1f0e-8803-4f2d-b2a0-25b8f86db929

**Comment by intamixx** [comment]
Hello,
Thanks, I can see the multer field is too long (when everything is checked) as only one model (musicnn or discogs-effnet) can be used when submitting a job for an audiofile.

https://github.com/intamixx/matnn/commit/2ea6626d8515819b62a6bf1bca2e9f4b35a0298f

I've added a check in for this to prevent both from being checked.

**Comment by gingerbeardman** [comment]
Oh, right! It would make sense if those two were radio buttons instead of check marks?

**Comment by gingerbeardman** [comment]
I'm getting more pleasing genres from musicnn in my limited testing

but i'm not wedded to either at this point

**Comment by intamixx** [comment]
.
